[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200
board_build.f_cpu = 80000000L

lib_deps =
    ArduinoJson
    bodmer/TFT_eSPI                     # TFT 显示屏驱动

build_flags =
    -D USER_SETUP_LOADED=1              # 禁用 TFT_eSPI 默认 User_Setup.h
    -include $PROJECT_DIR/User_Setup_ST7735.h  # 加载自定义屏幕配置
